swagger: '2.0'
info:
  description: 'This is the [Aeternity](https://www.aeternity.com/) Testnet API.'
  version: 1.0.0
  title: Aeternity Testnet
  termsOfService: 'https://www.aeternity.com/terms/'
  contact:
    email: apiteam@aeternity.com
basePath: /v1
tags:
  - name: account
    description: Everything about your accounts
schemes:
  - http
paths:
  /account:
    post:
      tags:
        - account
      operationId: AddAccount
      summary: Add a new account
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Account object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '405':
          description: Invalid input
      security: []
  /top:
    get:
      tags:
        - top
      operationId: GetTop
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Top'
      security: []
  /keypair:
    get:
      tags:
        - keypair
      operationId: GetKeyPair
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/KeyPair'
      security: []
  /load-keypair:
    post:
      tags:
        - load-keypair
      operationId: LoadKeyPair
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/LoadKeyPair'
      responses:
        '405':
          description: Invalid input
      security: []
  /peer:
    post:
      tags:
        - peer
      operationId: AddPeer
      summary: Add a new peer
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Peer object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Peer'
      responses:
        '405':
          description: Invalid input
      security: []
  /new-channel-with-server:
    post:
      tags:
        - new-channel-with-server
      operationId: NewChannelWithServer
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/NewChannelWithServer'
      responses:
        '405':
          description: Invalid input
      security: []
  /spend:
    post:
      tags:
        - spend
      operationId: Spend
      summary: Spend
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Spend object
          required: true
          schema:
            $ref: '#/definitions/Spend'
      responses:
        '405':
          description: Invalid input
      security: []
  /channel-spend:
    post:
      tags:
        - channel-spend
      operationId: ChannelSpend
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/ChannelSpend'
      responses:
        '405':
          description: Invalid input
      security: []
  /lightning-spend:
    post:
      tags:
        - lightning-spend
      operationId: LightningSpend
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/LightningSpend'
      responses:
        '405':
          description: Invalid input
      security: []
  /pull-channel-state:
    post:
      tags:
        - pull-channel-state
      operationId: PullChannelState
      summary: ''
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/PullChannelState'
      responses:
        '405':
          description: Invalid input
      security: []
definitions:
  Account:
    type: object
    properties:
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
  Top:
    type: object
    properties:
      hash:
        type: string
      height:
        type: integer
        format: int64
  KeyPair:
    type: object
    properties:
      public:
        type: string
      private:
        type: string
  LoadKeyPair:
    type: object
    properties:
      public:
        type: string
      private:
        type: string
      brain-wallet:
        type: string
  Peer:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
  Spend:
    type: object
    properties:
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
  NewChannelWithServer:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
      channel-id:
        type: integer
        format: int64
      balance:
        type: integer
        format: int64
      receive-limit:
        type: integer
        format: int64
      fee:
        type: integer
        format: int64
      delay:
        type: integer
        format: int64
  ChannelSpend:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
      amount:
        type: integer
        format: int64
  LightningSpend:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
      fee:
        type: integer
        format: int64
  PullChannelState:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
externalDocs:
  description: Find out more about Aeternity
  url: 'http://www.aeternity.com'
