swagger: '2.0'
info:
  description: 'This is the [Aeternity](https://www.aeternity.com/) Testnet API.'
  version: 1.0.0
  title: Aeternity Testnet
  termsOfService: 'https://www.aeternity.com/terms/'
  contact:
    email: apiteam@aeternity.com
basePath: /v1
tags:
  - name: account
    description: Everything about your accounts
schemes:
  - http
paths:
  /account:
    post:
      tags:
        - account
      operationId: AddAccount
      summary: Add a new account
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Account object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '405':
          description: Invalid input
      security: []
  /top:
    get:
      tags:
        - top
      operationId: GetTop
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Top'
      security: []
  /keypair:
    get:
      tags:
        - keypair
      operationId: GetKeyPair
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/KeyPair'
      security: []
  /peer:
    post:
      tags:
        - peer
      operationId: AddPeer
      summary: Add a new peer
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Peer object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Peer'
      responses:
        '405':
          description: Invalid input
      security: []
definitions:
  Account:
    type: object
    properties:
      pubkey:
        type: string
      amount:
        type: integer
        format: int64
  Top:
    type: object
    properties:
      hash:
        type: string
      height:
        type: integer
        format: int64
  KeyPair:
    type: object
    properties:
      public:
        type: string
      private:
        type: string
  Peer:
    type: object
    properties:
      ip:
        type: string
      port:
        type: integer
        format: int16
externalDocs:
  description: Find out more about Aeternity
  url: 'http://www.aeternity.com'
